### ISSUE TITLE
Task, implementation, tests, Maven

### ISSUE THREAD

**Issue by Suntrie** [Polinacherkay/SecondTask#1]
0. По заданию папка поиска может быть не указана - тогда поиск должен вестись в той папке cmd, в которой Вы будете находится в cmd при запуске утилиты ("."). **Upd.** Актуально;

1. <s>С точки зрения реализации - используемая библиотека позволяет задавать требуемые и опциональные аргументы (см. аннотацию "required"). **Upd.** Кроме этого, для хранения адресов предназначены объекты класса Path, а не строки</s>;

<s>2. Что происходит здесь:
```
} catch (e: CmdLineException) {
                System.err //?
                return
            }
```
- пока неочевидно. В целом же, при нормальном завершении метода main (не по ошибке) return не требуется;</s>

<s>3. FindFile. Метод find, вроде, в текущей реализации будет статическим. **Upd.** Актуально;</s>

4. <s>Там же. Вот так:
`Paths.get(directory + "\\" + filename)` - лучше не делать по двум причинам: 
- разделители путей в разных ОС будут различными
- cуществует метод Paths.get, позволяющий задавать аргументы через запятую;**Upd.** Про разделители - все еще актуально, пока у меня в Linux по этой причине падают тесты с ошибкой:</s> 
```
java.lang.AssertionError: 
Expected :[input\empty.txt]
Actual   :[input/empty.txt]
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:32)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at org.example.FindTest.findFile(FindTest.kt:12)

```

<s>5. Там же. Вызов
`val allDir = allFiles.toList()` делает не то, чего Вы от него ожидаете; **Upd.** Стало лучше, но на предупреждения от инспекций - стоит обращать внимание. Что сейчас будет, если Вам по пути попадется пустая папка? Что вернет listFiles в таком случае?</s>

<s>6. Тесты. Использовать абсолютные пути в тестах - некорректно, потому что они не будут воиспроизводиться у Ваших коллег. Пути задают относительно корня проекта (можно щелкнуть по файлу в Project Navigator Идеи и выбрать "Copy path... relative);</s> **Upd.** Смотрите комментарий 4.

<s>7. Тесты. Их, очевидно, должно быть больше. В частности, хотелось бы, чтобы Вы рассмотрели use-case-ы с рекурсией, отсутствующими искомыми файлами, поиском в текущей папке;</s>

8. Maven. Зачем Вы выгружаете папку /lib - с учетом того, что подключаете args4j как внешнюю библиотеку через pom.xml - пока также не до конца поняла. **Upd.** Кроме этого, [оформление проекта на Котлин в виде Maven-проекта](https://kotlinlang.org/docs/reference/using-maven.html), вообще говоря, требует добавления в билд плагина (хотя Идея позволяет Вам обойтись и без этого);

<s>9. Find. Действительно ли область видимости переменных должна быть public?</s>

**Comment by Suntrie** [comment]
0. Попробуйте, пожалуйста, протестировать, задав параметры вручную через Run- Edit configurations... (как это можно сделать, можно посмотреть в пояснениях ко второй работе). В текущей реализации работа с дефолтной папкой вроде будет осуществляться не так, как Вы планировали. Кроме этого, действительно ли при каких-то вариантах развития событий будет возможна ситуация в FindFile -> findFile, при которой вызов Paths.get(directory.toString()).toFile() вернет null?

----
7. В структуре Maven-проектов предусмотрена [директория для хранения тестовых ресурсов](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html);
